"""Added field chat_owner

Revision ID: c4cff08e26a2
Revises: ef18c82c1958
Create Date: 2025-04-12 17:17:30.316640

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4cff08e26a2"
down_revision: Union[str, None] = "ef18c82c1958"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "chat", "appuser", ["owner_id"], ["id"])
    op.drop_column("message", "read_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column(
            "read_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "chat", type_="foreignkey")
    op.drop_column("chat", "owner_id")
    # ### end Alembic commands ###
