"""Removed friends

Revision ID: ef18c82c1958
Revises: 7dc2b769e17e
Create Date: 2025-03-19 23:06:10.077406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ef18c82c1958"
down_revision: Union[str, None] = "7dc2b769e17e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("friendrequest")
    op.drop_table("friend")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friend",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "friend_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["friend_id"], ["appuser.id"], name="friend_friend_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["appuser.id"], name="friend_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="friend_pkey"),
    )
    op.create_table(
        "friendrequest",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "sender_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "receiver_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending", "accepted", "denied", name="requeststatus"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["receiver_id"],
            ["appuser.id"],
            name="friendrequest_receiver_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["appuser.id"], name="friendrequest_sender_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="friendrequest_pkey"),
    )
    # ### end Alembic commands ###
